### ISSUE TITLE
Configuring browser version is not working

### ISSUE THREAD

**Issue by Math-llm-lab** [CheshireCaat/selenium-with-fingerprints#12]
The program idea is cool, but how can I test it?

I downloaded the file with supported versions,
[
  {
    "architecture": "x64",
    "bas_version": "26.0.2",
    "browser_type": "chromium_connector",
    **"browser_version": "115.0.5790.99",**
    "description": "",
    "id": 4,
    "is_null": false
  },
  {
    "architecture": "x64",
    "bas_version": "26.0.0",
    "browser_type": "chromium_connector",
    **"browser_version": "114.0.5735.91",**
    "description": "",
    "id": 3,
    "is_null": false
  }
]

I tried each of them using:
// Use a specific version:
plugin.version = '114.0.5735.91';
but it still downloads the latest 116.
**How exactly should I download them?**

By the way, for example, with version 116, I downloaded it and compared it with my profiles on the website
https://bot.sannysoft.com/ and
I didn't see any changes in the main fingerprint parameters.

**How can I verify that the fingerprint is changing?**

**Comment by bablosoft** [comment]
> but it still downloads the latest 116.

116 is not supported yet. You probably downloading normal version not selenium-with-fingerprints

**Comment by Math-llm-lab** [comment]
**I'm interested in purchasing your product**as it seems to be a great fit for my profiles.!

However, before making a purchase, I would like to verify a few aspects of the plugin's functionality.

Firstly, I would like to confirm whether the plugin indeed has the capability to **modify fingerprint parameters**. 
Additionally, I'm interested in knowing if it's possible t**o connect a folder with Chrome profile data** without requiring migration to Chromium

I have attempted various approaches...

I even tried uninstalling all Chrome versions and installed only the compatible 114.0.5735.91 version!

During testing, I executed your script, first resulting in this image...
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/8ea04c6a-6e81-427e-a359-dfb22d2ba53a)

Subsequently, I encountered an error
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/35638ff6-1d6c-49ec-96c8-932842a845c1)

I noticed that there was a commented line "// const { Builder } = require('selenium-webdriver');" i (**is it correct ?** )

However, this led to another error :
**Selenium Manager binary found at C:\Users\....\selenium-with-fingerprints\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe
The chromedriver version (114.0.5735.90) detected in PATH at C:\Users\...\chromedriver.exe might not be compatible with the detected chrome version (116.0.5845.96); currently, chromedriver 116.0.5845.96 is recommended for chrome 116.*, so it is advised to delete the driver in PATH and retry
Driver path: C:\Users\...\chromedriver.exe
Browser path: C:\Users\...\.cache\selenium\chrome\win64\116.0.5845.96\chrome.exe
[9036:14264:0819/014616.984:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.**

This is folder  C:\Users\...\.cache\selenium\chrome\win64\116.0.5845.96\chrome.exe was created selenium-manager 
I went to this folder and check json file **selenium-manager.json**
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/c85886e3-05d5-499d-879e-d79570532699)
Upon inspection, I found that the file contained incorrect information, pointing to version 116 which I don't have.

For check I try run **simple Selenium script** 
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/b7ca2223-99e0-42a7-b8d9-f6b0dfdc3d46)
and everything ok and I opened selenium-manager.json and it was correct
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/50843258-2bcf-46d4-aa91-263986582214)

I attempted to modify the start script using "selenium-with-fingerprint" and included the browser version, but unfortunately, it didn't yield any positive results.
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/a05768bb-4239-461d-8fe2-04aefd8d58d3)

Most likely, this is related to the interaction between the "selenium-with-fingerprints" plugin and Selenium, specifically with selenium-manager. By the way, this is not an isolated case of issues arising after the release of version 116.

Please provide assistance in resolving this issue. After the issue is addressed, I'm ready to conduct thorough testing of your product, and if it functions as expected, I'll consider purchasing it.

Thank you for your attention to this matter, and I hope for your support and resolution and I am looking forward to purchasing your product.
