### ISSUE TITLE
Issues with launching after the release of Chrome 116.

### ISSUE THREAD

**Issue by Math-llm-lab** [CheshireCaat/selenium-with-fingerprints#13]
**I'm interested in purchasing your product**as it seems to be a great fit for my profiles.!

However, before making a purchase, I would like to verify a few aspects of the plugin's functionality.

Firstly, I would like to confirm whether the plugin indeed has the capability to **modify fingerprint parameters**. 
Additionally, I'm interested in knowing if it's possible t**o connect a folder with Chrome profile data** without requiring migration to Chromium

I have attempted various approaches...

I even tried uninstalling all Chrome versions and installed only the compatible 114.0.5735.91 version!

During testing, I executed your script, first resulting in this image...
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/8ea04c6a-6e81-427e-a359-dfb22d2ba53a)

Subsequently, I encountered an error
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/35638ff6-1d6c-49ec-96c8-932842a845c1)

I noticed that there was a commented line "// const { Builder } = require('selenium-webdriver');" i (**is it correct ?** )

However, this led to another error :
**Selenium Manager binary found at C:\Users\....\selenium-with-fingerprints\node_modules\selenium-webdriver\bin\windows\selenium-manager.exe
The chromedriver version (114.0.5735.90) detected in PATH at C:\Users\...\chromedriver.exe might not be compatible with the detected chrome version (116.0.5845.96); currently, chromedriver 116.0.5845.96 is recommended for chrome 116.*, so it is advised to delete the driver in PATH and retry
Driver path: C:\Users\...\chromedriver.exe
Browser path: C:\Users\...\.cache\selenium\chrome\win64\116.0.5845.96\chrome.exe
[9036:14264:0819/014616.984:ERROR:chrome_browser_cloud_management_controller.cc(163)] Cloud management controller initialization aborted as CBCM is not enabled.**

This is folder  C:\Users\...\.cache\selenium\chrome\win64\116.0.5845.96\chrome.exe was created selenium-manager 
I went to this folder and check json file **selenium-manager.json**
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/c85886e3-05d5-499d-879e-d79570532699)
Upon inspection, I found that the file contained incorrect information, pointing to version 116 which I don't have.

For check I try run **simple Selenium script** 
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/b7ca2223-99e0-42a7-b8d9-f6b0dfdc3d46)
and everything ok and I opened selenium-manager.json and it was correct
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/50843258-2bcf-46d4-aa91-263986582214)

I attempted to modify the start script using "selenium-with-fingerprint" and included the browser version, but unfortunately, it didn't yield any positive results.
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/a05768bb-4239-461d-8fe2-04aefd8d58d3)

Most likely, this is related to the interaction between the "selenium-with-fingerprints" plugin and Selenium, specifically with selenium-manager. By the way, this is not an isolated case of issues arising after the release of version 116.

Please provide assistance in resolving this issue. After the issue is addressed, I'm ready to conduct thorough testing of your product, and if it functions as expected, I'll consider purchasing it.

Thank you for your attention to this matter, and I hope for your support and resolution and I am looking forward to purchasing your product.

_Originally posted by @LuckHub22 in https://github.com/CheshireCaat/selenium-with-fingerprints/issues/12#issuecomment-1684385432_

**Comment by CheshireCaat** [comment]
You must use the exact same version of **chromedriver** that is installed for the browser, otherwise **selenium** may download and use the default browser instead.

The update with version **116** just came out, so now you can use the same version of the driver, otherwise install the right one.

**Comment by Math-llm-lab** [comment]
Thank you. I launch browser 116 without problem now
this code
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/a3c1d5ca-af21-493f-9147-f28456dd586c)
But fingerprints have not changed 

How can I test whether the fingerprint has changed in the free version? Can I execute the example stealth or other code to verify changes on test profiles?

**Comment by CheshireCaat** [comment]
Apparently, in the latest versions of `selenium` and `chromedriver`, the definition of the custom path to the browser was slightly changed and, in fact, broke:

https://github.com/SeleniumHQ/selenium/issues/12479
https://github.com/SeleniumHQ/selenium/issues/12604

Because of this, a regular browser was launched, which was loaded using `selenium` manager. Now you can downgrade `selenium-webdriver` version to `4.10.0`, it works correctly with it. Also, this problem has already been fixed on the side of the framework, but not yet in the release:

https://github.com/SeleniumHQ/selenium/issues/12479

Or you can manually patch the framework without waiting for the update by repeating this change:

https://github.com/SeleniumHQ/selenium/commit/ec2f0fb156259c0cb18f09e5031506f245b5fa37

Unfortunately, it will be problematic to automate this on the plugin side now.
After the release of version `4.12.0` or higher, you can update the framework - this should work. 

Until the new version of the framework is released, I will pin this ticket and will not close it.

**Comment by Math-llm-lab** [comment]
Yes, after downgrading to version 4.10.0, I am able to open the Chromium browser. However, I am still encountering new issues with the viewport.

![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/104425700/4320a4a5-e4f9-4082-9935-000ac2b2156c)

I have attempted various methods to launch the browser, but the problem with the viewport remains consistent. 
If the browser opens smaller than the width of the screen, it poses one issue. Additionally, if the browser opens larger than the width of the screen, it becomes problematic as I am unable to access the browser's settings menu.

 if it's not even possible to manually resize the browser window, then working becomes very inconvenient.
