### ISSUE TITLE
changeGeolocation always returns the same position

### ISSUE THREAD

**Issue by liguanquan** [CheshireCaat/selenium-with-fingerprints#14]
The settings for switching database and ip-api.com were not found
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/8055468/6d19fe66-d6eb-4fa9-973b-37d28edd4c6a)
In addition, can I pass the coordinates myself?

**Comment by bablosoft** [comment]
We will fix it in next versions.

**Comment by liguanquan** [comment]
Thank you
