### ISSUE TITLE
The fingerprint is detected as bot

### ISSUE THREAD

**Issue by vpolonic** [CheshireCaat/selenium-with-fingerprints#17]
const { plugin } = require('selenium-with-fingerprints');
fs = require("fs")

const key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx';

(async () => {

  let fingerprint = JSON.parse(fs.readFileSync('./fingerprint.json', 'utf8'));
  if(!fingerprint){
    fingerprint = await plugin.fetch(key, {
      tags: ['Microsoft Windows', 'Chrome'],
    });
    console.log('Fingerprint obtained:');
    fs.writeFileSync('./fingerprint.json', JSON.stringify(fingerprint, null, 2) , 'utf-8');
  }
  console.log('Fingerprint obtained:');

  console.log("Fingerprint loaded")
  const driver = await plugin.useFingerprint(fingerprint).launch();

  console.log("Driver inited")

  await driver.get('https://hmaker.github.io/selenium-detector/');

  //await driver.quit();
})();

Version Chromium: 119.0.6045.106

I check with:https://hmaker.github.io/selenium-detector/

![detected1](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/45886702/09453745-dc75-4341-aaca-b0ad6d952342)

I check with: fingerprint.com
![detected2](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/45886702/c555eafc-586c-48a9-b146-bf6e134f982f)

selenium-with-fingerprints it is detected as bot everywhere!

Also if I set the option with Mobile:
  fingerprint = await plugin.fetch(key, {
      tags: ['Mobile', 'Chrome'],
    });
 
![image](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/45886702/82c0c392-ae59-4188-b8cd-e8cc026c5eae)

It opens with a hundred times larger zoom!

**Comment by bablosoft** [comment]
When I've checked last time, selenium leaves traces. Please use BAS instead, it doesn't have that problem

https://bablosoft.com/shop/BrowserAutomationStudio#download

**Comment by vpolonic** [comment]
BAS does not allow many functionalities, for example I have not found anywhere how I can click on a button that has a phone number and extract that phone number

**Comment by bablosoft** [comment]
You can click by any css/xpath selector, coordinates, execute js and many more, that is enough to click anywhere and extract anything

**Comment by bablosoft** [comment]
Ah and also to click on elements found by image and text

**Comment by vpolonic** [comment]
I found a solution, and now it works!
![298164244-82c0c392-ae59-4188-b8cd-e8cc026c5eae](https://github.com/CheshireCaat/selenium-with-fingerprints/assets/45886702/87716968-8c72-4cce-ac2a-64859515d2da)

It remains to find a solution for displaying the browser, which is launched together with the fingerprint at extremely high parameters.
without the fingerprint it launches ok, together with the fingerprint it launches very big!
Do you have any idea where these parameters can be changed?
This does not work!!!
  console.log(
    'Viewport:',
    await driver.executeScript(() => ({
      deviceScaleFactor: window.devicePixelRatio,
      width: document.documentElement.clientWidth,
      height: document.documentElement.clientHeight,
    }))
  );
