### ISSUE TITLE
proposal: modify --user-data-dir option by default

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/selenium-with-fingerprints#2]
I suggest modifying the `user-data-dir` option in your library to point to a temporary directory like the user's temp directory instead of the `C:\Program Files (x86)` directory if the user does not provide a `user-data-dir` option in their script.
An alternative solution to fix this issue could be addressed on the Browser side, which I believe could be a better approach.

After running a simple script multiple times, I noticed that multiple directories were created in the `C:\Program Files (x86)` directory. I believe this happened because the browser is running with the data directory set to such location instead of a temporary directory.

Here is the script:
```javascript
// Import dependencies:
require('chromedriver');
const {plugin} = require('selenium-with-fingerprints');
const fs = require('fs');
const {promisify} = require('util');
const writeFileAsync = promisify(fs.writeFile);


// Main function:
(async () => {

    // Get a fingerprint from the server:
    const fingerprint = await plugin.fetch('', {
        tags: ['Microsoft Windows', 'Chrome'],
    });

    // Apply fingerprint:
    plugin.useFingerprint(fingerprint);

    // Launch the browser instance:
    const driver = await plugin.launch();

    // Maximize the window:
    await driver.manage().window().maximize();

    // Navigate to the website:
    await driver.get('https://fingerprintjs.github.io/BotD/main/');

    // Wait for the page to load:
    await driver.wait(async () => {
        const pageState = await driver.executeScript('return document.readyState');
        return pageState === 'complete';
    }, 10000);

    // Take a screenshot:
    const screenshot = await driver.takeScreenshot();

    // Save the screenshot to a file:
    await writeFileAsync('screenshot.png', screenshot, 'base64');

    // Quit the browser:
    await driver.quit();
})();

```
Automated Browser cmd:

```
C:/Users/Administrator/WebstormProjects/selenium-with-fingerprints-testing/data/run/FingerprintPlugin/d5219/browser/chrome/worker/worker.exe --allow-pre-commit-input --bas-force-visible-window --disable-background-networking --disable-backgrounding-occluded-windows --disable-client-side-phishing-detection --disable-default-apps --disable-features=NetworkServiceInProcess2 --disable-hang-monitor --disable-popup-blocking --disable-prompt-on-repost --disable-sync --enable-automation --enable-blink-features=ShadowDOMV0 --enable-logging --log-level=0 --no-first-run --no-proxy-server --no-sandbox --no-service-autorun --parent-process-id=762 --password-store=basic --remote-debugging-port=0 --test-type=webdriver --unique-process-id=xBmyv0KJ --use-mock-keychain 
--user-data-dir="C:\Program Files (x86)\scoped_dir8384_223478364" data:,
```

![1](https://user-images.githubusercontent.com/64213648/222901900-556581d4-908c-43d2-9a41-33d8f9a5461d.JPG)

**Comment by CheshireCaat** [comment]
Good day!

However, it seems to me that such things should be handled by the original framework - as, for example, `puppeteer` and `playwright` do.

Still, the plugin is an add-on to the original, and we want to add as few elements as possible that differ from the usual `selenium-webdriver`. Thus, there will be fewer **surprises** for users of the original framework

All in all, it's a good suggestion, I'll think about it.

**Comment by CheshireCaat** [comment]
Now, if the user does not specify a profile path, a temporary profile will be created in the `profiles` folder inside the engine directory - this applies to all plugins.
