### ISSUE TITLE
Extension support

### ISSUE THREAD

**Issue by bondobrus** [CheshireCaat/selenium-with-fingerprints#22]
Is there a way to add extension support for this plugin? If that is already possible please let me know. I couldn't add it myself

**Comment by CheshireCaat** [comment]
You can use a special [addExtensions](https://www.selenium.dev/selenium/docs/api/javascript/module-selenium-webdriver_chromium-Options.html#addExtensions) method for options, as is done for regular selenium, or load extensions via command-line arguments.

If there are problems with this, re-open the ticket and attach the code that can be used to reproduce the errors.
