### ISSUE TITLE
question: compatibility of user profiles between of your library and BAS

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/selenium-with-fingerprints#3]
I am writing to inquire about the compatibility of browser profiles created using your library and BAS. Specifically, I would like to know whether it is possible to use a browser profile created using your library with BAS, and vice versa. 

I understand that to ensure compatibility, it is important that both tools (your library and BAS) use the same browser versions.

**Comment by CheshireCaat** [comment]
I think the profiles will be compatible - given that the browser version will be the same.

However, **BAS** profiles can also store a fingerprint and a proxy in separate files - the logic for saving this data will need to be done independently on the your code side.

Anyway, I'll check it myself when I have time.

**Comment by CheshireCaat** [comment]
At this point in time, profiles are compatible, including browser components, `widevine` and so on.

**Comment by bablosoft** [comment]
> The only difference is that the plugin does not save the fingerprint and proxy to the profile folder, you need to do it yourself.

I just tested with `puppeteer-with-fingerprints` and it seems that fingerprint.json and proxy.txt are save to profile folder correctly.

Is it not the case for selenium?

**Comment by CheshireCaat** [comment]
@bablosoft you are right, there is no difference between the plugins, I will correct the answer above.
