### ISSUE TITLE
Question: Any possibility to pass it to python?

### ISSUE THREAD

**Issue by AlexPaiva** [CheshireCaat/selenium-with-fingerprints#5]
Love this solution, any ideas to use it in python?

**Comment by sergerdn** [comment]
> Love this solution, any ideas to use it in python?

Well, I need it too. I have an untested idea:

- To spawn a browser using this library from Python or another language
- To connect to the spawned browser using Python or another language.

https://github.com/CheshireCaat/selenium-with-fingerprints#launching-the-browser

Original code from docs:

```javascript
const { Builder } = require('selenium-webdriver');
const { Options } = require('selenium-webdriver/chrome');
const { plugin } = require('selenium-with-fingerprints');

const chrome = await plugin.spawn({ headless: true });

//  Any code below this line can be rewritten with Python:


const driver = await new Builder()
  .forBrowser('chrome')
  .setChromeOptions(new Options().debuggerAddress(`localhost:${chrome.port}`))
  .build();

await driver.quit();
await chrome.close();
```

Solution (untested pseudo code):
```python 
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium_with_fingerprints import plugin # we haven't it yet, we have only for javascript

"""
Instead of running this code, execute an external script that returns the port.
chrome = plugin.spawn(headless=True)
""""

driver = webdriver.Chrome(options=Options().debugger_address(f"localhost:{chrome.port}"))

driver.quit()
chrome.close()
```

But please note that @CheshireCaat mentioned in another issue:
> .. will need to manually call the `chrome.configure()` method after opening each page.

https://github.com/CheshireCaat/selenium-with-fingerprints/issues/4#issuecomment-1455134659

I have no idea how we should handle this in such a case, or if we need to do anything at all.

**Comment by AlexPaiva** [comment]
> > Love this solution, any ideas to use it in python?
> 
> Well, I need it too. I have an untested idea:
> 
>     * To spawn a browser using this library from Python or another language
> 
>     * To connect to the spawned browser using Python or another language.
> 
> 
> https://github.com/CheshireCaat/selenium-with-fingerprints#launching-the-browser
> 
> Original code from docs:
> 
> ```js
> const { Builder } = require('selenium-webdriver');
> const { Options } = require('selenium-webdriver/chrome');
> const { plugin } = require('selenium-with-fingerprints');
> 
> const chrome = await plugin.spawn({ headless: true });
> 
> //  Any code below this line can be rewritten with Python:
> 
> 
> const driver = await new Builder()
>   .forBrowser('chrome')
>   .setChromeOptions(new Options().debuggerAddress(`localhost:${chrome.port}`))
>   .build();
> 
> await driver.quit();
> await chrome.close();
> ```
> 
> Solution (untested pseudo code):
> 
> ```python
> from selenium import webdriver
> from selenium.webdriver.chrome.options import Options
> from selenium_with_fingerprints import plugin # we haven't it yet, we have only for javascript
> 
> """
> Instead of running this code, execute an external script that returns the port.
> chrome = plugin.spawn(headless=True)
> """"
> 
> driver = webdriver.Chrome(options=Options().debugger_address(f"localhost:{chrome.port}"))
> 
> driver.quit()
> chrome.close()
> ```
> 
> But please note that @CheshireCaat mentioned in another issue:
> 
> > .. will need to manually call the `chrome.configure()` method after opening each page.
> 
> [#4 (comment)](https://github.com/CheshireCaat/selenium-with-fingerprints/issues/4#issuecomment-1455134659)
> 
> I have no idea how we should handle this in such a case, or if we need to do anything at all.

Not easy to implement such a thing

**Comment by sergerdn** [comment]
> Not easy to implement such a thing

If this idea is not easy for you to implement, you can consider hiring developers to help you with its implementation. 
However, please keep in mind that this is only an idea, and there is **no guarantee of its success**.

**Comment by kaliiiiiiiiii** [comment]
@AlexPaiva [Selenium-Profiles](https://github.com/kaliiiiiiiiii/Selenium-Profiles) might help you partially

**Comment by jeffward01** [comment]
> Love this solution, any ideas to use it in python?

I plan to port this in C#, but first, I think more bug testing is needed to ensure it is 'stable' for a port.

You dont want to port it, then re-write it again.

Thanks for this awesome library!! @CheshireCaat

**Comment by sergerdn** [comment]
@AlexPaiva

I have tested my idea, and it works. You can take a look at the basic implementation here: https://github.com/sergerdn/playwright-with-fingerprints-python.

**Comment by AlexPaiva** [comment]
> @AlexPaiva
> 
> I have tested my idea, and it works. You can take a look at the basic implementation here: https://github.com/sergerdn/playwright-with-fingerprints-python.

Never worked with bas, how to set your git up and test it?

**Comment by sergerdn** [comment]
> > @AlexPaiva
> > I have tested my idea, and it works. You can take a look at the basic implementation here: https://github.com/sergerdn/playwright-with-fingerprints-python.
> 
> Never worked with bas, how to set your git up and test it?

What exactly would you like to know? I have created a Git project, written a basic README, and also wrote some code to explain my idea.
