### ISSUE TITLE
ChromeDriver error

### ISSUE THREAD

**Issue by undefinedteam1** [CheshireCaat/selenium-with-fingerprints#6]
Hi team, 

I installed by npm command (version 1.1.2) and can not start chrome because version of chrome and chromedriver not is same.

![image](https://user-images.githubusercontent.com/77137924/223011379-9d739c4f-705f-4e0d-b9c4-0c9798abd1e7.png)

I'm trying install version 1.1.3 but the package not found

Please update version or change package.json,

Thanks

**Comment by CheshireCaat** [comment]
Please, check-out [documentation](https://github.com/CheshireCaat/selenium-with-fingerprints#dependencies) and other [issues](https://github.com/CheshireCaat/selenium-with-fingerprints/issues/1) before creating a new one.
