### ISSUE TITLE
Regeneration of package-lock.json file upon running npm install

### ISSUE THREAD

**Issue by sergerdn** [CheshireCaat/selenium-with-fingerprints#8]
Here's what I did:
- Forked your project.
- Cloned the forked project.
- Ran `npm install` to install all the dependencies.
- Got a new version of the `package-lock.json` file.

Note: I tried to run `npm i --lockfile-version 1` and `npm i --lockfile-version 1 --package-lock-only` instead of `npm install`, but the `package-lock.json` file was still upgraded.

I'm planning to suggest some changes to your project, but I'm concerned that modifying the `package-lock.json` file could cause conflicts with my pull request.

System information:
- npm version: 9.5.1 (installed by running `npm install -g npm@latest`)
- NodeJS version: v18.14.2 (the latest LTS version at the moment)

Do I miss something? Let me know if there's anything else you need from me.

**Comment by bablosoft** [comment]
So use npm ci instead. We don't provide consultations on how js or npm works. Please don't post anything unrelated to this repo.

**Comment by sergerdn** [comment]
Thank you for the detailed answer. I appreciate it, and it will be very helpful to me.

I'm sorry if I've been a bother to the maintainers of this project, especially you. However, I want to assure you that I always try to resolve my issues before posting anything on GitHub or elsewhere.

Also, please note that in any issues in GitHub, other users can also reply, not only maintainers.

Additionally, you may prefer to use GitHub discussions for your users in some cases, especially for their "stupid noob questions," to prevent opening unrelated issues for this project.
