### ISSUE TITLE
How to run Selenium after applying fingerprint.json stored in the local folder

### ISSUE THREAD

**Issue by developers-dev** [CheshireCaat/selenium-with-fingerprints#9]
The fingerprint.json file is already stored in the local directory through the fingerprint switcher. Is there any way to apply this?

**Comment by sergerdn** [comment]
Take a look https://github.com/CheshireCaat/puppeteer-with-fingerprints/issues/4

**Comment by developers-dev** [comment]
Dear @sergerdn   
I am a beginner. can you help?

Question 1
My file (fingerprint.json - generated by fingerprint switcher) starts with {"canvas... blah blah ~ 
but the file generated with the code above starts with {\"valid\":true,\"plugins\".. blah blah~
Is there any problem if I apply fingerprints that are different like this?

Question 2
It seems to be the code to enter the profile path before launching the browser.
`const profileDirectory = path.join(os.tmpdir(), ".profile-cookies-test");`

By the way, where should I enter the path to the fingerprint.json file stored in the local directory?

**Comment by sergerdn** [comment]
@developers-dev.

You should know that I have very limited experience with JavaScript, especially with this library.
1. No, it might not be a problem for you.
2. Well, copy and paste my code into ChatGPT and ask what each line is doing.

**Comment by CheshireCaat** [comment]
Closed due to lack of activity.
